### ISSUE TITLE
Error while parsing

### ISSUE THREAD

**Issue by DanielBakovic** [kuma-giyomu/JSONParser#5]
Hi, I get the following error while parsing a json feed:

Fatal error: Uncaught exception 'Exception' with message 'Lexical Error: Unmatched Input.' in  package\JSONLex.php on line 3475

![test-feed json](https://cloud.githubusercontent.com/assets/1132636/2590041/e237b0fe-ba55-11e3-8d11-9b81bfff90e3.png)

I've uploaded the json feed file. Had to rename it to "png". You should remove ".png" file extension to get the json file.

Best regards,
Daniel

**Comment by marcosfreitas** [comment]
Hey guys, This same error has ocurred with me when I'm parsing a very large JSON file and I can't fix this. Please help me.

> Fatal error: Uncaught exception 'Exception' with message 'Lexical Error: Unmatched Input.' in C:\wamp\www\nexcabo\wp-content\plugins\c4n-grade-canais\JSONParser\package\JSONLex.php on line 3733
> ( ! ) Exception: Lexical Error: Unmatched Input. in C:\wamp\www\nexcabo\wp-content\plugins\c4n-grade-canais\JSONParser\package\JSONLex.php on line 3733

I've upload the json file if it help you: [download the big JSON of list of programs](https://drive.google.com/file/d/0B4mgTK9wetCqNVg2Y203TVhQQms/view?usp=sharing)

**Comment by kuma-giyomu** [comment]
Cheers, I'll have a look at that in the coming days. Thanks for reporting.

**Comment by kuma-giyomu** [comment]
It turns out your JSON is not valid.

It's a massive file so it's a bit tricky to validate it but it chokes on the value for the `sinopse` key for "Escavadores - O Tesouro do Barba Negra". Now if you check the value, you'll see this:

``` text
(...)"titulo" : "Escavadores - O Tesouro do Barba Negra","sinopse" : ""KG e Ringy estão na Carolina do Norte, bus(...)
```

The sinopse key is closing the value immediately (notice the `""` before the value actually begins)

Try running the following command to see it by yourself.

``` bash
sed 's/},{/},\n{/g' grade.json | grep --text "Escavadores - O Tesouro do Barba Negra"
```

**Comment by marcosfreitas** [comment]
OMG, thank you.
