### ISSUE TITLE
Does not work in PHP 5.6?

### ISSUE THREAD

**Issue by jcfiala** [kuma-giyomu/JSONParser#6]
Hi.

We're using this parser - it's great - but we ran into an issue on environments with PHP 5.6 installed - we got this error:
```
Undefined offset: 65536
exception 'ErrorException' with message 'Undefined offset: 65536' in /Users/nino/Documents/gitdev/spire/dcon56/digital-consulting/app/helpers/JSONParser/JSONLex.php:3486
Stack trace:
#0 /Users/nino/Documents/gitdev/spire/dcon56/digital-consulting/app/helpers/JSONParser/JSONLex.php(3486): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', '/Users/nino/Doc...', 3486, Array)
```

(with more stack trace steps below, but I don't think they're as useful).

I noticed that 65536 is eight times the 8192 character chunk that you're reading in - I'm not sure what's going on with that.

However, it works fine in PHP 5.4, so that's fine for us.

**Comment by kuma-giyomu** [comment]
Thanks for the bug report. I had a quick look and it seems to be an issue with the lexer code being generated. A character map table is too big (8k ish entries) and somehow causes PHP 5.6 to be unable to read the content of the array.

I'll try to get it done today.

**Comment by kuma-giyomu** [comment]
I modified the parser generator by breaking down into smaller arrays and I have it running fine on PHP 5.6.7. Let me know how you fare.

**Comment by kuma-giyomu** [comment]
A side note, you'll need to update the submodule.
