### ISSUE TITLE
How to have the php array ?

### ISSUE THREAD

**Issue by Snowji-Yama** [kuma-giyomu/JSONParser#8]
Hello,

I would try your parser but i don't understand one thing.

After parserDocument(), how to give the final php array ?

Thanks

**Comment by kuma-giyomu** [comment]
I think you are trying to use this library in a way it was not designed for.
The library does only provide hooks for you to fill in with whatever you want your code to achieve. It does not provide any facility for returning the complete structure. After all, if you load a 700MB JSON file into an object, its in memory representation will be ridiculously large as well. This library is well suited to analyse files and piecemeal the useful bits you are after.
Let's imagine you have the above 700MB file, composed of 100,000 smaller documents in an array. You could very well process each one individually, but not all at once.

What this parser provides is hooks that are triggered when the parser encounters specific elements of the document (new object, new property, closing an object, etc). It is up to you to take action, track the state and rebuild an object representation if you desire to do so.

This parser was inspired by the Java SAX parser (an XML parser).
You can have a look at the documentation https://docs.oracle.com/javase/tutorial/jaxp/sax/parsing.html, it will give you some insight on how to use the parser as it was designed.

More references:
https://en.wikipedia.org/wiki/Simple_API_for_XML

**Comment by Snowji-Yama** [comment]
Oh ok thanks a lot

**Comment by Snowji-Yama** [comment]
But do you know a technic to decode a large Json string in array php ?

**Comment by kuma-giyomu** [comment]
Well, if some subdocuments of your JSON data is loadable without exploding your memory, then yes, you can do it.
A very naive implementation would do this:
- parse the top document
- look for the events announcing the subdocuments you are interested in
- use the events to rebuild a string representation in a buffer
- once you get the even closing the subdocument you are interested in, feed the JSON string to `json_decode`
- do your magic with the decoded object and then trash it
- continue your top document parsing

In the end it boils down to waiting for the element you are interested in to trigger the action you want.
